###############################################################################
# Make file for Python Maple SDK
# 
# This SDK is mainly used for development and verification and while it may
# run on other systems, is it only expected to run on Posix machines
# (specifically Ubuntu and Raspbian OS).
###############################################################################

PYTHON_FILES := *.py
PY := python3.8

run: $(PYTHON_FILES)
	$(PY) main.py

